#!/bin/tcsh
if ($# < 1)  then
 exit
else
 gmtset GRID_CROSS_SIZE 0 ANOT_FONT_SIZE 10 PAPER_MEDIA a4

 set GRDINF=`grdinfo -C $1=1`
 echo $GRDINF
 
 set XMIN = `echo $GRDINF | cut -f2 -d' '`
 set XMAX = `echo $GRDINF | cut -f3 -d' '`
 set YMIN = `echo $GRDINF | cut -f4 -d' '`
 set YMAX = `echo $GRDINF | cut -f5 -d' '`
 echo $GRDINF
 echo $XMIN
 echo $XMAX
 echo $YMIN
 echo $YMAX
#GRDINF: FILE Xmin Xmax Ymin Ymax Zmin Zmax dX dY Nx Ny

 if ($# >= 2) then
   set NZ = $2;
 else
   set NZ = 20;
 endif
 
 if ($# >= 4) then
   set ZMIN = $3
   set ZMAX = $4
 else
   set ZMIN=`echo $GRDINF | gawk '{print $6;}'`
   set ZMAX=`echo $GRDINF | gawk '{print $7;}'`
 endif

set ZMIN=`echo $ZMIN | gawk '{printf("%0.2g",$1);}'`
set ZMAX=`echo $ZMAX | gawk '{printf("%0.2g",$1);}'`
set DZ=`echo $ZMIN | gawk -vZZMAX=$ZMAX -v NZZ=$NZ '{printf("%0.2g",(ZZMAX-$1)/NZZ);}'`

 echo $ZMIN  
 echo $ZMAX 
 echo $DZ
 
 makecpt $1=1 -I -Chaxby -T$ZMIN/$ZMAX/$DZ > g.cpt

gmtset GRID_CROSS_SIZE 0 ANOT_FONT_SIZE 10

#grdview $1=1 -Cg.cpt -E45/70 -JX10 -Jz-3.0 -S5 >> qq.ps

grdimage $1=1 -Y2 -Jx1 -Cg.cpt -Ba1g1ENW -K >! q.ps
psscale -Y-2 -D13c/1.5c/20c/0.5ch -Cg.cpt -V -O >> q.ps
#pscoast -JX15 -Dh -R$XMIN/$XMAX/$YMIN/$YMAX -W -O -K >> q.ps
#grdcontour $1=1 -Cg.cpt -A10 -JX15 -S5 -K -O >> q.ps
#psxy shot0.dat -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -Sa0.3c -G255/0/0 -O -K >> q.ps
#psxy rec.xyz -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -Si0.2c -G255/0/0 -O -K >> q.ps
#psxy ray0.xyz -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -Sc0.1c -G0/255/0 -O -K >> q.ps
#psxy ray0_f15.xyz -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -Sc0.1c -G0/0/255 -O -K >> q.ps
#psbasemap -Ba25/a25 -U$1 -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -O >> q.ps 
ggv q.ps
endif
