#!/bin/tcsh

2dgmt interface_it$1.2d interface_it$1.gmt 153 153 0. 0. 0.1
2dgmt modified_interface.2d modified_interface.gmt 153 153 0. 0. 0.1
grdmath modified_interface.gmt=1 interface_it$1.gmt=1 SUB mask.gmt=1 MUL = change_interface.gmt=1
pli change_interface.gmt
