#!/bin/csh
if ($# < 4)  then
 exit
else
 gmtset GRID_CROSS_SIZE 0 ANOT_FONT_SIZE 10 PAPER_MEDIA a4

 set GRDINF=`grdinfo -C $1=1`
 echo $GRDINF
 
 set XMIN = `echo $GRDINF | cut -f2 -d' '`
 set XMAX = `echo $GRDINF | cut -f3 -d' '`
 set YMIN = `echo $GRDINF | cut -f4 -d' '`
 set YMAX = `echo $GRDINF | cut -f5 -d' '`
 
set XMAX = 30
 
 echo $GRDINF
 echo $XMIN
 echo $XMAX
 echo $YMIN
 echo $YMAX
#GRDINF: FILE Xmin Xmax Ymin Ymax Zmin Zmax dX dY Nx Ny

set ZMIN=$2
set ZMAX=$3
set DZ=$4

 echo $ZMIN  
 echo $ZMAX 
 echo $DZ
 
 if ($# < 5)  then
   makecpt $1=1 -Chaxby -T$ZMIN/$ZMAX/$DZ -Z > g.cpt
 else
   makecpt $1=1 -C$5 -T$ZMIN/$ZMAX/$DZ -Z > g.cpt
 endif

gmtset GRID_CROSS_SIZE 0 ANOT_FONT_SIZE 10 LABEL_FONT_SIZE 12

#grdview $1=1 -Cg.cpt -E45/70 -JX10 -Jz-3.0 -S5 >> qq.ps

grdimage $1=1 -JX15 -Cg.cpt -R$XMIN/$XMAX/$YMIN/$YMAX  -Ba10:"Normalized hit counts":/a0.15:"Angular coverage, radian":WSen -K >! q.ps
psscale -D16.5c/5c/10c/0.5c -Cg.cpt -B/:"Resolution": -V -O >> q.ps
#pscoast -JX15 -Dh -R$XMIN/$XMAX/$YMIN/$YMAX -W -O>> q.ps
#grdcontour $1=1 -Cg.cpt -A2 -JX15 -S5 -K -O >> q.ps
#psxy shot0.dat -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -Sa0.3c -G255/0/0 -O -K >> q.ps
#psxy rec.xyz -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -Si0.2c -G255/0/0 -O -K >> q.ps
#psxy ray0.xyz -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -Sc0.1c -G0/255/0 -O -K >> q.ps
#psxy ray0_f15.xyz -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -Sc0.1c -G0/0/255 -O -K >> q.ps
#psbasemap -Ba1/a1 -U$1 -JX15 -R$XMIN/$XMAX/$YMIN/$YMAX -O >> q.ps 
ggv q.ps
endif
